### ISSUE TITLE
Investigate error "CommandExecutionError: Failed To Open SCPolicySvc: Access is denied."

### ISSUE THREAD

**Issue by lorengordon** [plus3it/ash-windows-formula#36]
Error using `service.enabled` state with Salt 2016.11.1:

```
          ID: CCE-24365-9-Smart Card Removal Policy service must be enabled
    Function: service.enabled
        Name: SCPolicySvc
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1744, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1702, in wrapper
                  return f(*args, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\service.py", line 523, in enabled
                  ret.update(_enable(name, None, **kwargs))
                File "C:\salt\bin\lib\site-packages\salt\states\service.py", line 153, in _enable
                  if __salt__['service.enable'](name, **kwargs):
                File "C:\salt\bin\lib\site-packages\salt\modules\win_service.py", line 794, in enable
                  modify(name, start_type='Auto')
                File "C:\salt\bin\lib\site-packages\salt\modules\win_service.py", line 666, in modify
                  'Failed To Open {0}: {1}'.format(name, exc[2]))
              CommandExecutionError: Failed To Open SCPolicySvc: Access is denied.
     Started: 16:52:01.102000
    Duration: 62.0 ms
     Changes:
```

**Comment by lorengordon** [comment]
Can no longer reproduce the error. Closing.
